packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@hookform/resolvers": ^5.2.2
  "@preact/signals-react": ^3.6.1
  "@t3-oss/env-nextjs": ^0.13.8
  "@types/http-link-header": ^1.0.7
  class-variance-authority: ^0.7.1
  disable-devtool: ^0.3.9
  dotenv-cli: ^11.0.0
  http-link-header: ^1.1.3
  jiti: ^2.6.1
  postcss: ^8.5.6
  react-hook-form: ^7.68.0
  sass: ^1.94.2
  sonner: ^2.0.7
  swagger-jsdoc: ^6.2.8
  swagger-ui-express: ^4.6.2

catalogs:
  drizzle0.44:
    "@types/pg": ^8.15.6
    drizzle-orm: ^0.44.7
    drizzle-kit: ^0.31.7
    drizzle-zod: ^0.8.3
    pg: ^8.16.3

  emotion11:
    "@emotion/cache": ^11.14.0
    "@emotion/react": ^11.14.0
    "@emotion/styled": ^11.14.1

  eslint9:
    "@eslint/compat": ^2.0.0
    "@eslint/js": ^9.39.1
    eslint: ^9.39.1
    eslint-plugin-import: ^2.32.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^7.0.1

  mui7:
    "@mui/icons-material": ^7.3.6
    "@mui/material": ^7.3.6
    "@mui/material-nextjs": ^7.3.6
    "@mui/x-data-grid": ^8.15.0
    "@mui/x-data-grid-premium": ^8.15.0
    "@mui/x-data-grid-pro": ^8.15.0

  uuid13:
    uuid: ^13.0.0

  next16:
    "@clerk/nextjs": ^6.35.6
    "@next/eslint-plugin-next": ^16.0.7
    next: ^16.0.7
    next-intl: ^4.5.8

  node24:
    "@types/node": ^24.10.1

  prettier3:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.7.4
    prettier-plugin-tailwindcss: ^0.7.2

  qrcode:
    "@types/qrcode.react": ^3.0.0
    qrcode.react: ^4.2.0

  radix-ui1:
    "@radix-ui/react-icons": ^1.3.2
    radix-ui: ^1.4.3

  react19:
    "@types/react": ~19.2.7
    "@types/react-dom": ^19.2.3
    react: ^19.2.1
    react-dom: ^19.2.1

  react-query5:
    "@tanstack/react-query": ^5.90.11
    "@tanstack/react-query-devtools": ^5.91.1

  superjson2:
    superjson: ^2.2.6

  tailwind4:
    "@tailwindcss/forms": ^0.5.10
    "@tailwindcss/postcss": ^4.1.17
    "autoprefixer": ^10.4.22
    tailwindcss: ^4.1.17
    tw-animate-css: ^1.4.0
    tailwind-merge: ^3.4.0

  turbo2:
    "@turbo/gen": ^2.6.3
    eslint-plugin-turbo: ^2.6.3
    turbo: ^2.6.3

  trpc11:
    "@trpc/client": ^11.7.2
    "@trpc/server": ^11.7.2
    "@trpc/tanstack-react-query": ^11.7.2

  typescript5:
    typescript: ^5.9.3
    typescript-eslint: ^8.48.1

  zod4:
    zod: ^4.1.13

onlyBuiltDependencies:
  - esbuild

overrides:
  minimatch: ^10.1.1

nodeLinker: hoisted
linkWorkspacePackages: true
